### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by amommendes** [hamzakpt/feast_astra#1]
Hey @hamzakpt,

Nice work! Could you provide some list (requirements.txt, setup.py, poetry, etc) of project dependencies?

**Comment by hamzakpt** [comment]
great thanks, i will add requirements.txt

**Comment by hamzakpt** [comment]
added requirement file, Thanks

**Comment by amommendes** [comment]
Very nice @hamzakpt ! Thanks!
